package com.example.nasaclient;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Toast;
import androidx.fragment.app.FragmentActivity;
import com.example.nasaclient.databinding.ActivityWithNavBinding;


public class PlanetActivity extends FragmentActivity {
    private static final String TAG = "PlanetActivity";
    ActivityWithNavBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityWithNavBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        getLayoutInflater().inflate(R.layout.activity_planets, binding.container, true);
        // Setup bottom navigation
        binding.bottomNavigationView.setSelectedItemId(R.id.home);
        binding.bottomNavigationView.setOnItemSelectedListener(item -> {
            int itemId = item.getItemId();
            if (itemId == R.id.home) {
                return true;
            } else if (itemId == R.id.planet) {
                startActivity(new Intent(this, PlanetActivity.class));
                return true;
            } else if (itemId == R.id.practice) {
                startActivity(new Intent(this, PracticeActivity.class));
                return true;
            } else if (itemId == R.id.setting) {
                startActivity(new Intent(this, SettingActivity.class));
                return true;
            }
            return false;
        });
        setupPlanetButtons();
    }

    private void setupPlanetButtons() {
        int[] buttonIds = {
                R.id.earthExploreButton,
                R.id.mercuryExploreButton,
                R.id.venusExploreButton,
                R.id.marsExploreButton,
                R.id.saturnExploreButton,
                R.id.uranusExploreButton,
                R.id.neptuneExploreButton,
        };

        for (int id : buttonIds) {
            View button = findViewById(id);
            if (button != null) {
                button.setOnClickListener(this::onExploreButtonClick);
                Log.d(TAG, "Button set up: " + getResources().getResourceEntryName(id));
            } else {
                Log.e(TAG, "Button not found: " + getResources().getResourceEntryName(id));
            }
        }
    }

    public void onExploreButtonClick(View view) {
        Log.d(TAG, "Button clicked: " + view.getId());

        Intent intent = new Intent(this, PlanetInfoActivity.class);

        int viewId = view.getId();
        if (viewId == R.id.earthExploreButton) {
            Log.d(TAG, "Earth button clicked");
            intent.putExtra("PLANET_NAME", "Earth");
            intent.putExtra("PLANET_IMAGE", R.drawable.earth);
            intent.putExtra("PLANET_INFO", "Earth is the third planet from the Sun and has a diverse, life-supporting environment. It is a terrestrial planet with a core composed of iron and nickel, a solid surface with mountains, valleys, and vast oceans, and a protective atmosphere rich in nitrogen and oxygen." + "Earth’s magnetic field, generated by its spinning core, helps shield us from harmful solar and cosmic radiation. It also causes the mesmerizing auroras in polar regions when particles from the Sun interact with the atmosphere.");

        } else if (viewId == R.id.mercuryExploreButton) {
            Log.d(TAG, "Mercury button clicked");
            intent.putExtra("PLANET_NAME", "Mercury");
            intent.putExtra("PLANET_IMAGE", R.drawable.mercury);
            intent.putExtra("PLANET_INFO", "Mercury, the smallest and innermost planet in the Solar System, is rocky with a metallic core that makes up a significant portion of its mass. It has no atmosphere to trap heat, resulting in scorching daytime temperatures and freezing nights. The surface is heavily cratered, similar to the Moon’s Despite being closest to the Sun, Mercury is not the hottest planet—that title goes to Venus. Mercury’s lack of atmosphere allows it to cool down significantly at night, while Venus’s thick atmosphere traps heat.");
        } else if (viewId == R.id.marsExploreButton) {
            Log.d(TAG, "Mars button clicked");
            intent.putExtra("PLANET_NAME", "Mars");
            intent.putExtra("PLANET_IMAGE", R.drawable.mars);
            intent.putExtra("PLANET_INFO", "Mars, often called the \"Red Planet,\" has a cold desert landscape covered in iron oxide, which gives it a red color. It has two polar ice caps, and evidence of ancient river beds suggests that water once flowed on its surface. The planet has the largest volcano, Olympus Mons, and the deepest canyon, Valles Marineris.Mars has seasons similar to Earth due to its tilted axis. However, its atmosphere is thin, composed mostly of carbon dioxide, so temperatures are much colder than Earth’s, and the surface can only support very thin layers of frozen water at present.");
        } else if (viewId == R.id.venusExploreButton) {
            Log.d(TAG, "Venus button clicked");
            intent.putExtra("PLANET_NAME", "Venus");
            intent.putExtra("PLANET_IMAGE", R.drawable.venus);
            intent.putExtra("PLANET_INFO", "Venus, the second planet from the Sun, is similar in size and composition to Earth, but its thick atmosphere creates a runaway greenhouse effect, making it the hottest planet in our Solar System. The atmosphere, composed mostly of carbon dioxide, traps heat and has clouds of sulfuric acid, creating extreme surface pressures.Venus rotates slowly and in the opposite direction (retrograde rotation) compared to most other planets. A day on Venus is longer than a Venusian year, and it experiences little variation in temperature between day and night due to its thick atmosphere.");
        } else if (viewId == R.id.saturnExploreButton) {
            Log.d(TAG, "Saturn button clicked");
            intent.putExtra("PLANET_NAME", "Saturn");
            intent.putExtra("PLANET_IMAGE", R.drawable.saturn);
            intent.putExtra("PLANET_INFO", "Saturn is the sixth planet from the Sun and the second-largest in our Solar System. It is a gas giant with a complex system of rings made of ice, rock, and dust, creating one of the most beautiful celestial features. Saturn’s low density means it could float in water if there were a pool big enough.Saturn’s moon Titan has lakes of liquid methane and ethane and a thick atmosphere, making it one of the most Earth-like bodies in the Solar System. Titan and Saturn’s other moons contribute to the complexity of Saturn’s ring system through gravitational interactions.");
        } else if (viewId == R.id.neptuneExploreButton) {
            Log.d(TAG, "Neptune button clicked");
            intent.putExtra("PLANET_NAME", "Neptune");
            intent.putExtra("PLANET_IMAGE", R.drawable.neptune);
            intent.putExtra("PLANET_INFO", "Neptune, the eighth planet from the Sun, is a deep blue gas giant with strong atmospheric storms and supersonic winds that can reach over 1,200 miles per hour (2,000 kilometers per hour). Its atmosphere is mostly hydrogen, helium, and methane, which gives the planet its blue color.Neptune has a thin set of rings and 14 known moons, with Triton being the largest. Triton has geysers that shoot nitrogen gas into space, and it orbits Neptune in the opposite direction of the planet’s rotation, suggesting it was likely captured by Neptune’s gravity.");
        } else if (viewId == R.id.uranusExploreButton) {
            Log.d(TAG, "Uranus button clicked");
            intent.putExtra("PLANET_NAME", "Uranus");
            intent.putExtra("PLANET_IMAGE", R.drawable.uranus);
            intent.putExtra("PLANET_INFO", "Uranus is an ice giant, distinguished by its pale blue-green color, which comes from methane in its atmosphere. It has a unique axial tilt of about 98 degrees, meaning it essentially rotates on its side. Scientists believe this tilt may have been caused by a collision with an Earth-sized object billions of years ago.Uranus has 13 known rings and 27 moons, with most of its moons named after characters from the works of William Shakespeare and Alexander Pope. Its extreme tilt leads to unusual seasonal cycles, with each pole experiencing 42 years of continuous sunlight or darkness.");
        } else {
            Log.e(TAG, "Unknown button clicked: " + viewId);
            Toast.makeText(this, "Unknown planet selected", Toast.LENGTH_SHORT).show();
            return;
        }

        startActivity(intent);
    }}